import os
from typing import Any, Dict, List, Optional

from app.logger import logger
from app.tool.base import BaseTool, ToolResult
from pydantic import Field
from tavily import TavilyClient


class TavilyTool(BaseTool):
    name: str = "tavily_search"
    description: str = (
        "Performs a web search using the Tavily API. "
        "Use this tool to find information on the internet, get answers to questions, "
        "and retrieve content from webpages. It is faster and more reliable than browsing."
    )
    parameters: dict = {
        "type": "object",
        "properties": {
            "query": {
                "type": "string",
                "description": "The search query to execute.",
            },
            "search_depth": {
                "type": "string",
                "enum": ["basic", "advanced"],
                "default": "basic",
                "description": "The depth of the search. 'basic' is faster, 'advanced' is more thorough.",
            },
            "include_answer": {
                "type": "boolean",
                "default": False,
                "description": "Whether to include a short answer generated by Tavily.",
            },
            "max_results": {
                "type": "integer",
                "default": 5,
                "description": "The maximum number of search results to return.",
            },
        },
        "required": ["query"],
    }

    def _get_client(self) -> Optional[TavilyClient]:
        api_key = os.environ.get("TAVILY_API_KEY")
        if not api_key:
            logger.error("TAVILY_API_KEY not found in environment variables")
            return None
        return TavilyClient(api_key=api_key)

    async def execute(
        self,
        query: str,
        search_depth: str = "basic",
        include_answer: bool = False,
        max_results: int = 5,
    ) -> ToolResult:
        client = self._get_client()
        if not client:
            return ToolResult(
                error="Tavily API key is missing. Please set TAVILY_API_KEY in .env."
            )

        try:
            logger.info(f"🔍 Searching Tavily for: {query}")
            response = client.search(
                query=query,
                search_depth=search_depth,
                include_answer=include_answer,
                max_results=max_results,
            )

            output_lines = []
            if include_answer and response.get("answer"):
                output_lines.append(f"**Answer:** {response['answer']}\n")

            output_lines.append("**Search Results:**")
            for result in response.get("results", []):
                title = result.get("title", "No Title")
                url = result.get("url", "#")
                content = result.get("content", "")
                output_lines.append(f"- **[{title}]({url})**")
                output_lines.append(f"  {content}\n")

            return ToolResult(output="\n".join(output_lines))

        except Exception as e:
            logger.error(f"Error executing Tavily search: {e}")
            return ToolResult(error=f"Tavily search failed: {str(e)}")
